// generated file
export default {
  "primary_color": "#1890ff",
  "info_color": "#1890ff",
  "success_color": "#52c41a",
  "processing_color": "#1890ff",
  "error_color": "#f5222d",
  "highlight_color": "#f5222d",
  "warning_color": "#fa8c16",
  "normal_color": "#d9d9d9",
  "white": "#fff",
  "black": "#000",
  "body_background": "#fff",
  "component_background": "#fff",
  "line_height_base": 1.5,
  "font_family": "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'PingFang SC', 'Hiragino Sans GB',\n    'Microsoft YaHei', 'Helvetica Neue', Helvetica, Arial, sans-serif, 'Apple Color Emoji',\n    'Segoe UI Emoji', 'Segoe UI Symbol'",
  "text_color_inverse": "#fff",
  "icon_color": "inherit",
  "border_radius_base": "4px",
  "border_radius_sm": "2px",
  "font_size_base": "14px",
  "font_size_lg": "16px",
  "font_size_sm": "12px",
  "text_color": "#000",
  "text_color_secondary": "#0000005c",
  "border_color_base": "#d9d9d9",
  "border_color_split": "#e8e8e8",
  "border_color_inverse": "#fff",
  "border_width_base": "1px",
  "border_style_base": "solid",
  "outline_blur_size": 0,
  "outline_width": "2px",
  "outline_color": "#1890ff",
  "background_color_light": "#fafafa",
  "background_color_base": "#f5f5f5",
  "disabled_color": "#000",
  "disabled_bg": "#f5f5f5",
  "disabled_color_dark": "#f5f5f5",
  "padding_lg": "24px",
  "padding_md": "16px",
  "padding_sm": "12px",
  "padding_xs": "8px",
  "ease_base_out": "cubic-bezier(0.7, 0.3, 0.1, 1)",
  "ease_base_in": "cubic-bezier(0.9, 0, 0.3, 0.7)",
  "ease_out": "cubic-bezier(0.215, 0.61, 0.355, 1)",
  "ease_in": "cubic-bezier(0.55, 0.055, 0.675, 0.19)",
  "ease_in_out": "cubic-bezier(0.645, 0.045, 0.355, 1)",
  "ease_out_back": "cubic-bezier(0.12, 0.4, 0.29, 1.46)",
  "ease_in_back": "cubic-bezier(0.71, -0.46, 0.88, 0.6)",
  "ease_in_out_back": "cubic-bezier(0.71, -0.46, 0.29, 1.46)",
  "ease_out_circ": "cubic-bezier(0.08, 0.82, 0.17, 1)",
  "ease_in_circ": "cubic-bezier(0.6, 0.04, 0.98, 0.34)",
  "ease_in_out_circ": "cubic-bezier(0.78, 0.14, 0.15, 0.86)",
  "ease_out_quint": "cubic-bezier(0.23, 1, 0.32, 1)",
  "ease_in_quint": "cubic-bezier(0.755, 0.05, 0.855, 0.06)",
  "ease_in_out_quint": "cubic-bezier(0.86, 0, 0.07, 1)",
  "btn_font_weight": 400,
  "btn_border_width": "1px",
  "btn_border_style": "solid",
  "btn_primary_shadow": "0 2px 0 rgba(0, 0, 0, 0.045)",
  "btn_shadow": "0 2px 0 rgba(0, 0, 0, 0.015)",
  "btn_text_shadow": "0 -1px 0 rgba(0, 0, 0, 0.12)",
  "btn_group_border": "#096dd9",
  "btn_height_base": "32px",
  "btn_height_lg": "40px",
  "btn_height_sm": "24px",
  "btn_padding_base": "0 16px 1px",
  "btn_padding_lg": "0 16px 1px",
  "btn_padding_sm": "0 8px 1px",
  "btn_border_radius_base": "4px",
  "btn_border_radius_sm": "4px",
  "btn_border_radius_lg": "4px",
  "btn_font_size_base": "14px",
  "btn_font_size_lg": "16px",
  "btn_font_size_sm": "14px",
  "btn_circle_size_base": "32px",
  "btn_circle_size_lg": "40px",
  "btn_circle_size_sm": "24px",
  "btn_color_base": "#000",
  "btn_bg_base": "#fff",
  "btn_border_base": "#d9d9d9",
  "btn_color_hovered_base": "#40a9ff",
  "btn_color_active_base": "#096dd9",
  "btn_border_hovered_base": "#40a9ff",
  "btn_border_active_base": "#096dd9",
  "btn_bg_hovered_base": "#fff",
  "btn_bg_active_base": "#fff",
  "btn_color_primary": "#fff",
  "btn_color_hovered_primary": "#40a9ff",
  "btn_color_active_primary": "#fff",
  "btn_border_primary": "#d9d9d9",
  "btn_bg_primary": "#1890ff",
  "btn_bg_hovered_primary": "#40a9ff",
  "btn_bg_active_primary": "#096dd9",
  "btn_color_disable": "#000",
  "btn_bg_disable": "#f5f5f5",
  "btn_border_disable": "#d9d9d9",
  "btn_color_danger": "#fff",
  "btn_bg_danger": "#ff4d4f",
  "btn_border_danger": "#ff4d4f",
  "btn_bg_hovered_danger": "#ff7875",
  "btn_bg_active_danger": "#d9363e"
}